language: python
os: linux
dist: focal
python:
  - 3.6
  - 3.7

#branches:
#  only:
#    - master

addons:
  apt:
    update: true
#    packages: 
    
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

install:
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda info -a
  - conda create -n neutron_imaging python=$TRAVIS_PYTHON_VERSION
  - source activate neutron_imaging
  - bash config_conda_env.sh
  - cd notebooks
  - export PYTHONPATH=$PWD:$PYTHONPATH

script:
  - pytest -v
